kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-deploy
  labels:
    app: spring-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: spring-app

  template:
    metadata:
      labels:
        app: spring-app

    spec:
      containers:
        - name: spring-container
          image: chetu20/spring-boot:1.3
          ports:
            - containerPort: 8080
